models/orderdetails.py
from utils.db import db


class OrderDetail(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    orderId = db.Column(db.Integer, nullable=False)
    description = db.Column(db.String(50), nullable=True)
    quantity = db.Column(db.Integer, nullable=False)
    unitCost = db.Column(db.Integer, nullable=False)
    totalCost = db.Column(db.Integer, nullable=False)

    def __init__(self, orderId, quantity, description, unitCost, totalCost) -> None:
        self.orderId = orderId
        self.description = description
        self.quantity = quantity
        self.unitCost = unitCost
        self.totalCost = totalCost

    def __repr__(self) -> str:
        return f"Order({self.id}, {self.orderId}, '{self.description}', '{self.quantity}', '{self.unitCost}', '{self.totalCost}')"

routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from forms.registerForm import RegisterForm
from forms.loginForm import LoginForm
from utils.bcryptService import bcrypt
from models.user import User
from utils.db import db

auth = Blueprint("auth", __name__)


@auth.route("/")
def home():
    return render_template("home.html")


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            if bcrypt.check_password_hash(currentUser.password, password):
                login_user(currentUser)
                return redirect(url_for("auth.dashboard"))
    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        hashed_password = bcrypt.generate_password_hash(password)
        newUser = User(username, hashed_password, "active", "user")
        db.session.add(newUser)
        db.session.commit()
        return redirect(url_for("auth.login"))
    return render_template("register.html", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/dashboard")
@login_required
def dashboard():
    print(f"current_user: {current_user}")
    return render_template("dashboard.html", user=current_user)

routes/orderdetails.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from forms.orderDetailCreateForm import OrderDetailCreateForm
from utils.db import db
from models.orders import Order
from models.orderdetails import OrderDetail

orderDetails = Blueprint("orderDetails", __name__, url_prefix="/orderDetails")


@orderDetails.route("/")
@login_required
def home():
    orderDetailList = OrderDetail.query.all()
    return render_template("orderDetails/homegeneral.html", user=current_user, items = orderDetailList)

@orderDetails.route("/home<int:orderId>")
@login_required
def homeByOrderId(orderId):
    currentOrder = Order.query.filter_by(id=orderId).first()
    orderDetailList = OrderDetail.query.filter_by(orderId=orderId).all()
    return render_template("orderDetails/home.html", order=currentOrder, user=current_user, items=orderDetailList, orderId=orderId)

@orderDetails.route("/create/<int:orderId>", methods=["GET", "POST"])
@login_required
def createByOrderId(orderId):
    form = OrderDetailCreateForm(orderId=orderId)
    if form.validate_on_submit():
        currentOrder = Order.query.filter_by(id=orderId).first()

        quantity = form.quantity.data
        description = form.description.data
        unitCost = form.unitCost.data
        totalCost = quantity * unitCost
        currentOrder.totalSale += totalCost

        newOrderDetail = OrderDetail(orderId, quantity, description, unitCost, totalCost)
        db.session.add(newOrderDetail)
        db.session.add(currentOrder)
        db.session.commit()
        return redirect(url_for("orderDetails.homeByOrderId", orderId=orderId))
    return render_template("orderDetails/create.html", form=form, user=current_user, orderId=orderId)

@orderDetails.route("/delete/<int:id>/<int:orderId>")
@login_required
def delete(id, orderId):
    currentOrderDetail = OrderDetail.query.get(id)
    
    #Eliminar el total
    currentOrder = Order.query.filter_by(id=orderId).first()
    currentOrder.totalSale -= currentOrderDetail.totalCost
    
    db.session.add(currentOrder)
    db.session.delete(currentOrderDetail)
    db.session.commit()
    
    return redirect(url_for("orderDetails.homeByOrderId", orderId=orderId))

@orderDetails.route("/update/<int:id>/<int:orderId>", methods=["GET", "POST"])
@login_required
def updateByOrderId(id, orderId):
    currentDetail = OrderDetail.query.filter_by(id=id).first()    
    form = OrderDetailCreateForm(orderId=orderId, quantity=currentDetail.quantity, description=currentDetail.description, unitCost=currentDetail.unitCost)
    if form.validate_on_submit():
        currentOrder = Order.query.filter_by(id=orderId).first()
        currentOrder.totalSale -= currentDetail.totalCost

        currentDetail.quantity = form.quantity.data
        currentDetail.description = form.description.data
        currentDetail.unitCost = form.unitCost.data
        currentDetail.totalCost = currentDetail.quantity * currentDetail.unitCost
        currentOrder.totalSale += currentDetail.totalCost

        db.session.add(currentDetail)
        db.session.add(currentOrder)
        db.session.commit()
        print(id, orderId)
        return redirect(url_for("orderDetails.homeByOrderId",id=id,  orderId=orderId))
    return render_template("orderDetails/update.html", form=form, user=current_user, id=id, orderId=orderId)        
        
@orderDetails.route("/report/<int:orderId>")
@login_required
def report(orderId):
    currentOrder = Order.query.filter_by(id=orderId).first()
    orderDetailList = OrderDetail.query.filter_by(orderId=orderId).all()
    total_con_descuento = currentOrder.totalSale*(1-(currentOrder.discount)/100)
    total_impuesto = round(total_con_descuento*(1+(currentOrder.tax)/100),2)
    return render_template("orderDetails/report.html", order=currentOrder, user=current_user, items=orderDetailList, total_ajustado =total_impuesto)

templates/orderDetails/create.html
{% extends 'layout.html' %}
{% block title %}Agregar detalles de orden{% endblock %}
{% block contents %}
<h1>Agregar detalles de orden</h1>
<br>
{% if user %}
<p>Hello, {{user.username}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">Logout</a>
{% endif %}
<p>Por favor agregue el detalle de orden aquí:</p>
<br>
<form action="{{ url_for('orderDetails.createByOrderId', orderId=orderId) }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.orderId.label }}
    {{ form.orderId }}
    {{ form.description.label }}
    {{ form.description }}
    {{ form.quantity.label }}
    {{ form.quantity }}
    {{ form.unitCost.label }}
    {{ form.unitCost }}
    {{ form.submit }}
</form>

{% endblock %}

templates/orderDetails/home.html
{% extends 'layout.html' %}
{% block title %}Detalles de orden{% endblock %}
{% block contents %}
<h1>Detalles de orden</h1>
<br>
{% if user %}
<p>Hello, {{user.username}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">Logout</a>
{% endif %}
<p>Resumen de los detalles de orden: </p>
<br>
{% if order %}
<p>Orden:</p>
<ul>
    <li>{{ order.id }}</li>
    <li>{{ order.buyer }}</li>
    <li>{{ order.provider }}</li>
    <li>$ {{ order.totalSale }}</li>
</ul>
<br>
<a href="{{ url_for('orders.home') }}">Todas las órdenes</a>
<br>
{% endif %}
<br>
<a href="{{ url_for('orderDetails.createByOrderId', orderId=orderId) }}">Agregar detalle a la orden</a>
<br>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>IdOrden</th>
            <th>Descripción</th>
            <th>Cantidad</th>
            <th>Costo Unitario</th>
            <th>Costo Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.orderId }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.unitCost }}</td>
            <td>{{ item.totalCost }}</td>
            <td><a href="{{url_for('orderDetails.updateByOrderId', id=item.id, orderId=item.orderId)}}">actualizar</a></td>
            <td><a href="{{url_for('orderDetails.delete', id=item.id, orderId=orderId)}}">borrar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/orderDetails/homegeneral.html
{% extends 'layout.html' %}
{% block title %}Detalles de órdenes general{% endblock %}
{% block contents %}
<h1>Detalles de órdenes general</h1>
<br>
{% if user %}
<p>Hello, {{user.username}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">Logout</a>
{% endif %}
<p>Resuen general de todos los detalles de orden</p>
<br>
<p>Para añadir, actualizar o borrar un detalle, seleccione una orden aquí: <a href="{{ url_for('orders.home') }}">Órdenes</a></p>
<br>
<br>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>IdOrden</th>
            <th>Descripción</th>
            <th>Cantidad</th>
            <th>Costo Unitario</th>
            <th>Costo Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.orderId }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.unitCost }}</td>
            <td>{{ item.totalCost }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/orderDetails/report.html
{% extends 'layout.html' %}
{% block title %}Página de reporte{% endblock %}
{% block contents %}
<h1>Reporte de orden</h1>
<br>
{% if user %}
<p>Hello, {{user.username}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">Logout</a>
{% endif %}
<br>
<p>Este es un reporte al estilo factura de la orden.</p>
<p>Reporte de la orden seleccionada:</p>
{% if order %}
<p>Orden: {{ order.id}}</p>
<ul>
    <li>Total: $ {{ order.totalSale }}</li>
    <li>Descuento: {{ order.discount }} %</li>
    <li>Impuesto: {{ order.tax }} %</li>
    <li>Total a pagar: $ {{ total_ajustado }}</li>
</ul>
{% endif %}
<br>
<br>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>IdOrden</th>
            <th>Descripción</th>
            <th>Cantidad</th>
            <th>Costo Unitario</th>
            <th>Costo Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.orderId }}</td>
            <td>{{ item.description }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.unitCost }}</td>
            <td>{{ item.totalCost }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/orderDetails/update.html
{% extends 'layout.html' %}
{% block title %}Actualizar detalles de orden{% endblock %}
{% block contents %}
<h1>Actualizar detalles</h1>
<br>
{% if user %}
<p>Hola, {{user.username}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">Logout</a>
{% endif %}
<p>Por favor actualice los detalles aquí:</p>
<br>
<form action="{{ url_for('orderDetails.updateByOrderId', id=id, orderId=orderId) }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.orderId.label }}
    {{ form.orderId }}
    {{ form.description.label }}
    {{ form.description }}
    {{ form.quantity.label }}
    {{ form.quantity }}
    {{ form.unitCost.label }}
    {{ form.unitCost }}
    {{ form.submit }}
</form>

{% endblock %}