forms/loginForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class LoginForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("login")

forms/registerForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import InputRequired, Length, ValidationError
from models.user import User


class RegisterForm(FlaskForm):
    username = StringField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "username"},
    )

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(min=4, max=20),
        ],
        render_kw={"placeholder": "password"},
    )

    submit = SubmitField("register")

    def validate_username(self, username):
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            raise ValidationError("the username already exists")

routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from forms.registerForm import RegisterForm
from forms.loginForm import LoginForm
from utils.bcryptService import bcrypt
from models.user import User
from utils.db import db

auth = Blueprint("auth", __name__)


@auth.route("/")
def home():
    return render_template("home.html")


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            if bcrypt.check_password_hash(currentUser.password, password):
                login_user(currentUser)
                return redirect(url_for("auth.dashboard"))
    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        hashed_password = bcrypt.generate_password_hash(password)
        newUser = User(username, hashed_password, "active", "user")
        db.session.add(newUser)
        db.session.commit()
        return redirect(url_for("auth.login"))
    return render_template("register.html", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/dashboard")
@login_required
def dashboard():
    print(f"current_user: {current_user}")
    return render_template("dashboard.html", user=current_user)

routes/orderdetails.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from forms.orderDetailCreateForm import OrderDetailCreateForm
from utils.db import db
from models.orders import Order
from models.orderdetails import OrderDetail

orderDetails = Blueprint("orderDetails", __name__, url_prefix="/orderDetails")


@orderDetails.route("/")
@login_required
def home():
    orderDetailList = OrderDetail.query.all()
    return render_template("orderDetails/homegeneral.html", user=current_user, items = orderDetailList)

@orderDetails.route("/home<int:orderId>")
@login_required
def homeByOrderId(orderId):
    currentOrder = Order.query.filter_by(id=orderId).first()
    orderDetailList = OrderDetail.query.filter_by(orderId=orderId).all()
    return render_template("orderDetails/home.html", order=currentOrder, user=current_user, items=orderDetailList, orderId=orderId)

@orderDetails.route("/create/<int:orderId>", methods=["GET", "POST"])
@login_required
def createByOrderId(orderId):
    form = OrderDetailCreateForm(orderId=orderId)
    if form.validate_on_submit():
        currentOrder = Order.query.filter_by(id=orderId).first()

        quantity = form.quantity.data
        description = form.description.data
        unitCost = form.unitCost.data
        totalCost = quantity * unitCost
        currentOrder.totalSale += totalCost

        newOrderDetail = OrderDetail(orderId, quantity, description, unitCost, totalCost)
        db.session.add(newOrderDetail)
        db.session.add(currentOrder)
        db.session.commit()
        return redirect(url_for("orderDetails.homeByOrderId", orderId=orderId))
    return render_template("orderDetails/create.html", form=form, user=current_user, orderId=orderId)

@orderDetails.route("/delete/<int:id>/<int:orderId>")
@login_required
def delete(id, orderId):
    currentOrderDetail = OrderDetail.query.get(id)
    
    #Eliminar el total
    currentOrder = Order.query.filter_by(id=orderId).first()
    currentOrder.totalSale -= currentOrderDetail.totalCost
    
    db.session.add(currentOrder)
    db.session.delete(currentOrderDetail)
    db.session.commit()
    
    return redirect(url_for("orderDetails.homeByOrderId", orderId=orderId))

@orderDetails.route("/update/<int:id>/<int:orderId>", methods=["GET", "POST"])
@login_required
def updateByOrderId(id, orderId):
    currentDetail = OrderDetail.query.filter_by(id=id).first()    
    form = OrderDetailCreateForm(orderId=orderId, quantity=currentDetail.quantity, description=currentDetail.description, unitCost=currentDetail.unitCost)
    if form.validate_on_submit():
        currentOrder = Order.query.filter_by(id=orderId).first()
        currentOrder.totalSale -= currentDetail.totalCost

        currentDetail.quantity = form.quantity.data
        currentDetail.description = form.description.data
        currentDetail.unitCost = form.unitCost.data
        currentDetail.totalCost = currentDetail.quantity * currentDetail.unitCost
        currentOrder.totalSale += currentDetail.totalCost

        db.session.add(currentDetail)
        db.session.add(currentOrder)
        db.session.commit()
        print(id, orderId)
        return redirect(url_for("orderDetails.homeByOrderId",id=id,  orderId=orderId))
    return render_template("orderDetails/update.html", form=form, user=current_user, id=id, orderId=orderId)        
        
@orderDetails.route("/report/<int:orderId>")
@login_required
def report(orderId):
    currentOrder = Order.query.filter_by(id=orderId).first()
    orderDetailList = OrderDetail.query.filter_by(orderId=orderId).all()
    total_con_descuento = currentOrder.totalSale*(1-(currentOrder.discount)/100)
    total_impuesto = round(total_con_descuento*(1+(currentOrder.tax)/100),2)
    return render_template("orderDetails/report.html", order=currentOrder, user=current_user, items=orderDetailList, total_ajustado =total_impuesto)

templates/dashboard.html
{% extends 'layout.html' %}
{% block title %}Dashboard{% endblock %}
{% block contents %}
<h1>Dashboard</h1>
<br>
{% if user %}
<p>Hola, {{user.username}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">Logout</a>
{% endif %}
<p>Este es el dashboard principal:</p>
<br>
<a href="{{ url_for('orders.home') }}">Órdenes</a>
<br>
<a href="{{ url_for('orderDetails.home') }}">Detalles de órdenes</a>
<br>
<br>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}
{% block title %}Login{% endblock %}
{% block contents %}
<h1>Login/Registro para usuarios</h1>
<br>
<a href="{{ url_for('auth.login') }}">Login</a><br>
<a href="{{ url_for('auth.register') }}">Registrarse</a>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    {% block contents %}{% endblock %}
</body>

</html>

templates/login.html
{% extends 'layout.html' %}
{% block title %}login page{% endblock %}
{% block contents %}
<h1>login page</h1>
<br>
<form action="{{ url_for('auth.login') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username }}
    {{ form.password.label }}
    {{ form.password }}
    {{ form.submit }}
</form>
<br>
<a href="{{ url_for('auth.register') }}">Registrarse</a>
{% endblock %}

templates/register.html
{% extends 'layout.html' %}
{% block title %}Registro{% endblock %}
{% block contents %}
<h1>Página de registro</h1>
<br>
<form action="{{ url_for('auth.register') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.username.label }}
    {{ form.username }}
    {{ form.password.label }}
    {{ form.password }}
    {{ form.submit }}
</form>
<br>
<a href="{{ url_for('auth.login') }}">Login</a>
{% endblock %}