models/orders.py
from utils.db import db


class Order(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    buyer = db.Column(db.String(50), nullable=False)
    provider = db.Column(db.String(50), nullable=False)
    discount = db.Column(db.Integer, nullable=False)
    tax = db.Column(db.Integer, nullable=False)
    totalSale = db.Column(db.Integer, nullable=False)
    date = db.Column(db.String(50), nullable=True)

    

    def __init__(self, buyer, provider, discount, tax, totalSale=0, date=None) -> None:
        self.buyer = buyer
        self.provider = provider
        self.discount = discount
        self.tax = tax
        self.totalSale = totalSale
        self.date = date


    def __repr__(self) -> str:
        return f"Order({self.id}, {self.buyer}, '{self.provider}', '{self.discount}', '{self.tax}', '{self.totalSale}', '{self.date}')"

routes/auth.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from forms.registerForm import RegisterForm
from forms.loginForm import LoginForm
from utils.bcryptService import bcrypt
from models.user import User
from utils.db import db

auth = Blueprint("auth", __name__)


@auth.route("/")
def home():
    return render_template("home.html")


@auth.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        currentUser = User.query.filter_by(username=username).first()
        if currentUser:
            if bcrypt.check_password_hash(currentUser.password, password):
                login_user(currentUser)
                return redirect(url_for("auth.dashboard"))
    return render_template("login.html", form=form)


@auth.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        hashed_password = bcrypt.generate_password_hash(password)
        newUser = User(username, hashed_password, "active", "user")
        db.session.add(newUser)
        db.session.commit()
        return redirect(url_for("auth.login"))
    return render_template("register.html", form=form)


@auth.route("/logout")
def logout():
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/dashboard")
@login_required
def dashboard():
    print(f"current_user: {current_user}")
    return render_template("dashboard.html", user=current_user)

routes/orderdetails.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from forms.orderDetailCreateForm import OrderDetailCreateForm
from utils.db import db
from models.orders import Order
from models.orderdetails import OrderDetail

orderDetails = Blueprint("orderDetails", __name__, url_prefix="/orderDetails")


@orderDetails.route("/")
@login_required
def home():
    orderDetailList = OrderDetail.query.all()
    return render_template("orderDetails/homegeneral.html", user=current_user, items = orderDetailList)

@orderDetails.route("/home<int:orderId>")
@login_required
def homeByOrderId(orderId):
    currentOrder = Order.query.filter_by(id=orderId).first()
    orderDetailList = OrderDetail.query.filter_by(orderId=orderId).all()
    return render_template("orderDetails/home.html", order=currentOrder, user=current_user, items=orderDetailList, orderId=orderId)

@orderDetails.route("/create/<int:orderId>", methods=["GET", "POST"])
@login_required
def createByOrderId(orderId):
    form = OrderDetailCreateForm(orderId=orderId)
    if form.validate_on_submit():
        currentOrder = Order.query.filter_by(id=orderId).first()

        quantity = form.quantity.data
        description = form.description.data
        unitCost = form.unitCost.data
        totalCost = quantity * unitCost
        currentOrder.totalSale += totalCost

        newOrderDetail = OrderDetail(orderId, quantity, description, unitCost, totalCost)
        db.session.add(newOrderDetail)
        db.session.add(currentOrder)
        db.session.commit()
        return redirect(url_for("orderDetails.homeByOrderId", orderId=orderId))
    return render_template("orderDetails/create.html", form=form, user=current_user, orderId=orderId)

@orderDetails.route("/delete/<int:id>/<int:orderId>")
@login_required
def delete(id, orderId):
    currentOrderDetail = OrderDetail.query.get(id)
    
    #Eliminar el total
    currentOrder = Order.query.filter_by(id=orderId).first()
    currentOrder.totalSale -= currentOrderDetail.totalCost
    
    db.session.add(currentOrder)
    db.session.delete(currentOrderDetail)
    db.session.commit()
    
    return redirect(url_for("orderDetails.homeByOrderId", orderId=orderId))

@orderDetails.route("/update/<int:id>/<int:orderId>", methods=["GET", "POST"])
@login_required
def updateByOrderId(id, orderId):
    currentDetail = OrderDetail.query.filter_by(id=id).first()    
    form = OrderDetailCreateForm(orderId=orderId, quantity=currentDetail.quantity, description=currentDetail.description, unitCost=currentDetail.unitCost)
    if form.validate_on_submit():
        currentOrder = Order.query.filter_by(id=orderId).first()
        currentOrder.totalSale -= currentDetail.totalCost

        currentDetail.quantity = form.quantity.data
        currentDetail.description = form.description.data
        currentDetail.unitCost = form.unitCost.data
        currentDetail.totalCost = currentDetail.quantity * currentDetail.unitCost
        currentOrder.totalSale += currentDetail.totalCost

        db.session.add(currentDetail)
        db.session.add(currentOrder)
        db.session.commit()
        print(id, orderId)
        return redirect(url_for("orderDetails.homeByOrderId",id=id,  orderId=orderId))
    return render_template("orderDetails/update.html", form=form, user=current_user, id=id, orderId=orderId)        
        
@orderDetails.route("/report/<int:orderId>")
@login_required
def report(orderId):
    currentOrder = Order.query.filter_by(id=orderId).first()
    orderDetailList = OrderDetail.query.filter_by(orderId=orderId).all()
    total_con_descuento = currentOrder.totalSale*(1-(currentOrder.discount)/100)
    total_impuesto = round(total_con_descuento*(1+(currentOrder.tax)/100),2)
    return render_template("orderDetails/report.html", order=currentOrder, user=current_user, items=orderDetailList, total_ajustado =total_impuesto)

routes/orders.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from forms.orderCreateForm import OrderCreateForm
from utils.db import db
from models.orders import Order
from models.orderdetails import OrderDetail
from datetime import date

orders = Blueprint("orders", __name__, url_prefix="/orders")


@orders.route("/")
@login_required
def home():
    orderList = Order.query.all()
    return render_template("orders/home.html", items=orderList, user=current_user)


@orders.route("/create", methods=["GET", "POST"])
@login_required
def create():
    form = OrderCreateForm(provider=current_user.username)
    if form.validate_on_submit():
        buyer = form.buyer.data
        provider = form.provider.data
        discount = form.discount.data
        tax = form.tax.data
        newOrder = Order(buyer, provider, discount, tax)
        db.session.add(newOrder)
        db.session.commit()
        return redirect(url_for("orders.home"))
    return render_template("orders/create.html", form=form)


@orders.route("/finalize/<int:id>")
@login_required
def finalize(id):
    currentOrder = Order.query.get(id)
    currentDate = date.today().isoformat()
    currentOrder.date = currentDate
    db.session.add(currentOrder)
    db.session.commit()
    return redirect(url_for("orders.home"))

@orders.route("/delete/<int:id>")
@login_required
def delete(id):
    currentOrder = Order.query.get(id)
    OrderDetail.query.filter_by(orderId=id).delete()
    
    db.session.delete(currentOrder)
    db.session.commit()
    return redirect(url_for("orders.home"))

templates/orders/create.html
{% extends 'layout.html' %}
{% block title %}Agregar orden{% endblock %}
{% block contents %}
<h1>Agregar orden</h1>
<br>
{% if user %}
<p>Hola, {{user.username}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">logout</a>
{% endif %}
<p>Por favor complete los campos para crear la orden:</p>
<br>
<form action="{{ url_for('orders.create') }}" method="post">
    {{ form.hidden_tag() }}
    {{ form.buyer.label }}
    {{ form.buyer }}
    {{ form.provider.label }}
    {{ form.provider }}
    {{ form.discount.label }}
    {{ form.discount }}
    {{ form.tax.label }}
    {{ form.tax }}
    {{ form.submit }}
</form>

{% endblock %}

templates/orders/home.html
{% extends 'layout.html' %}
{% block title %}Órdenes{% endblock %}
{% block contents %}
<h1>Órdenes</h1>
{% if user %}
<p>Hola, {{user.username}}</p>
<br>
<a href="{{ url_for('auth.logout') }}">Logout</a>
{% endif %}
<p>Resumen de todas las órdenes: </p>
<br>
<a href="{{ url_for('orders.create') }}">Agregar nueva orden</a>
<br>
<table>
    <thead>
        <tr>
            <th>id</th>
            <th>Comprador</th>
            <th>Vendedor</th>
            <th>Descuento</th>
            <th>Impuesto</th>
            <th>Fecha</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for item in items %}
        <tr>
            <td>{{ item.id }}</td>
            <td>{{ item.buyer }}</td>
            <td>{{ item.provider }}</td>
            <td>{{ item.discount }}</td>
            <td>{{ item.tax }}</td>
            <td>{{ item.date }}</td>
            <td>{{ item.totalSale }}</td>
            <td><a href="{{ url_for('orderDetails.homeByOrderId', orderId=item.id) }}">Editar detalles</a></td>
            <td>
                {% if item.date == None %}
                <a href="{{ url_for('orders.finalize', id=item.id) }}">Finalizar</a>
                {% endif %}
            </td>
            <td><a href="{{ url_for('orders.delete', id=item.id) }}">Borrar</a></td>
            <td><a href="{{ url_for('orderDetails.report', orderId=item.id) }}">Ver reporte</a></td> 
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}